#ifndef ARTI_BRIDGE_H
#define ARTI_BRIDGE_H

#pragma once

/* Generated with cbindgen:0.27.0 */

/* Generated by cbindgen — do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#define ARTI_OK 0

#define ARTI_ERR_NULL -1

#define ARTI_ERR_UTF8 -2

#define ARTI_ERR_PANIC -3

#define ARTI_ERR_INIT -4

#define ARTI_ERR_ONION -5

#define ARTI_ERR_SHUTDOWN -6

#define ARTI_ERR_BOOTSTRAP -7

/**
 * Bootstrap mode passed to [`arti_init`].
 * - `0` — full bootstrap (synchronous; returns when ready). Foreground default.
 * - `1` — on-demand (returns immediately; circuits build lazily on first
 *   stream, or eagerly via [`arti_bootstrap`]). iOS BGProcessingTask warm path.
 */
#define ARTI_BOOTSTRAP_FULL 0

#define ARTI_BOOTSTRAP_ON_DEMAND 1

/**
 * Opaque handle. All FFI calls take `*mut ArtiHandle`.
 */
typedef struct ArtiHandle ArtiHandle;

/**
 * Status snapshot mirrored to Dart via an out-pointer. Layout MUST match
 * the FFI bindings in `lib/services/tor/ffi_bindings.dart`.
 */
typedef struct {
  uint32_t bootstrap_percent;
  uint32_t circuit_count;
  bool is_ready;
  uint16_t socks_port;
} ArtiStatus;

/**
 * Initialize Arti and return an opaque handle.
 *
 * `bootstrap_mode` selects how bootstrap proceeds:
 *   - [`ARTI_BOOTSTRAP_FULL`] (`0`) — synchronous full bootstrap; this call
 *     blocks until the client is ready for traffic. Foreground default.
 *   - [`ARTI_BOOTSTRAP_ON_DEMAND`] (`1`) — returns immediately after the
 *     client object is constructed; circuits are built lazily on first
 *     stream, or eagerly via [`arti_bootstrap`]. Plan 14 Phase D warm path
 *     for iOS BGProcessingTask.
 *
 * `data_dir` must be a NUL-terminated UTF-8 path; Arti stores its state,
 * circuit cache, and onion-service keypair here.
 *
 * On error returns NULL. The handle must be passed to [`arti_shutdown`]
 * to release resources.
 */
ArtiHandle *arti_init(const char *data_dir, uint8_t bootstrap_mode);

/**
 * Return a heap-allocated copy of the most recent error message produced
 * on this thread, or NULL if none has been recorded since the last clear.
 * The caller must free the returned string with [`arti_string_free`].
 *
 * Errors are stored per-thread; call this from the same thread that
 * observed the failing FFI return.
 */
char *arti_last_error(void);

/**
 * Publish the on-device HTTP server (listening on `127.0.0.1:local_port`)
 * as a v3 onion service. Returns the `<address>.onion` host on success,
 * or NULL on error. The caller must free the returned string with
 * [`arti_string_free`].
 *
 * The keypair lives under `<data_dir>/hs-state/<nickname>` so the address
 * is stable across restarts.
 */
char *arti_create_onion_service(ArtiHandle *handle, uint16_t local_port);

/**
 * Drive bootstrap explicitly. Idempotent and safe to call multiple times;
 * concurrent calls coalesce on the in-flight attempt (per
 * `TorClient::bootstrap`). Useful with [`ARTI_BOOTSTRAP_ON_DEMAND`] when
 * the caller wants to ensure the client is ready before issuing requests
 * — bound the wait via a Dart-side timeout, not in Rust.
 *
 * Returns [`ARTI_OK`] on success, [`ARTI_ERR_BOOTSTRAP`] on failure.
 */
int arti_bootstrap(ArtiHandle *handle);

/**
 * Returns the local SOCKS5 port Arti uses for outbound connections, or 0
 * if the SOCKS proxy isn't running. Used by Plan 11b to route the Dart
 * `http.Client` through Tor.
 */
uint16_t arti_socks_port(ArtiHandle *handle);

/**
 * Fill `out` with the latest status snapshot. Returns [`ARTI_OK`] or a
 * negative error code. `out` must point to a writable [`ArtiStatus`].
 */
int arti_status(ArtiHandle *handle, ArtiStatus *out);

/**
 * Drop the handle, tear down the runtime, and unpublish the onion
 * service. After this call, `handle` MUST NOT be used again.
 */
int arti_shutdown(ArtiHandle *handle);

/**
 * Free a string returned by [`arti_create_onion_service`].
 */
void arti_string_free(char *s);

#endif  /* ARTI_BRIDGE_H */
