#ifndef STARLING_BRIDGE_H
#define STARLING_BRIDGE_H

#pragma once

/* Generated with cbindgen:0.27.0 */

/* Generated by cbindgen — do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#define ARTI_OK 0

#define ARTI_ERR_NULL -1

#define ARTI_ERR_UTF8 -2

#define ARTI_ERR_PANIC -3

#define ARTI_ERR_INIT -4

#define ARTI_ERR_ONION -5

#define ARTI_ERR_SHUTDOWN -6

#define ARTI_ERR_BOOTSTRAP -7

/**
 * Bootstrap mode passed to [`arti_init`].
 * - `0` — full bootstrap (synchronous; returns when ready). Foreground default.
 * - `1` — on-demand (returns immediately; circuits build lazily on first
 *   stream, or eagerly via [`arti_bootstrap`]). iOS BGProcessingTask warm path.
 */
#define ARTI_BOOTSTRAP_FULL 0

#define ARTI_BOOTSTRAP_ON_DEMAND 1

#define LP_OK 0

#define LP_ERR_NULL -1

#define LP_ERR_UTF8 -2

#define LP_ERR_PANIC -3

#define LP_ERR_NOT_INITIALIZED -4

#define LP_ERR_LISTEN -5

#define LP_ERR_DIAL_TIMEOUT -6

#define LP_ERR_PROTOCOL -7

#define LP_ERR_STREAM_CLOSED -8

#define LP_ERR_BUFFER_TOO_SMALL -9

#define LP_ERR_UNIMPLEMENTED -10

/**
 * Opaque handle. All FFI calls take `*mut ArtiHandle`.
 */
typedef struct ArtiHandle ArtiHandle;

/**
 * Opaque handle returned by [`lp_init`].
 */
typedef struct LpHandle LpHandle;

/**
 * Status snapshot mirrored to Dart via an out-pointer. Layout MUST match
 * the FFI bindings in `lib/services/tor/ffi_bindings.dart`.
 */
typedef struct {
  uint32_t bootstrap_percent;
  uint32_t circuit_count;
  bool is_ready;
  uint16_t socks_port;
} ArtiStatus;

/**
 * Initialize Arti and return an opaque handle.
 *
 * `bootstrap_mode` selects how bootstrap proceeds:
 *   - [`ARTI_BOOTSTRAP_FULL`] (`0`) — synchronous full bootstrap; this call
 *     blocks until the client is ready for traffic. Foreground default.
 *   - [`ARTI_BOOTSTRAP_ON_DEMAND`] (`1`) — returns immediately after the
 *     client object is constructed; circuits are built lazily on first
 *     stream, or eagerly via [`arti_bootstrap`]. Plan 14 Phase D warm path
 *     for iOS BGProcessingTask.
 *
 * `data_dir` must be a NUL-terminated UTF-8 path; Arti stores its state,
 * circuit cache, and onion-service keypair here.
 *
 * On error returns NULL. The handle must be passed to [`arti_shutdown`]
 * to release resources.
 */
ArtiHandle *arti_init(const char *data_dir, uint8_t bootstrap_mode);

/**
 * Return a heap-allocated copy of the most recent error message produced
 * on this thread, or NULL if none has been recorded since the last clear.
 * The caller must free the returned string with [`arti_string_free`].
 *
 * Errors are stored per-thread; call this from the same thread that
 * observed the failing FFI return.
 */
char *arti_last_error(void);

/**
 * Publish the on-device HTTP server (listening on `127.0.0.1:local_port`)
 * as a v3 onion service. Returns the `<address>.onion` host on success,
 * or NULL on error. The caller must free the returned string with
 * [`arti_string_free`].
 *
 * The keypair lives under `<data_dir>/hs-state/<nickname>` so the address
 * is stable across restarts.
 */
char *arti_create_onion_service(ArtiHandle *handle, uint16_t local_port);

/**
 * Drive bootstrap explicitly. Idempotent and safe to call multiple times;
 * concurrent calls coalesce on the in-flight attempt (per
 * `TorClient::bootstrap`). Useful with [`ARTI_BOOTSTRAP_ON_DEMAND`] when
 * the caller wants to ensure the client is ready before issuing requests
 * — bound the wait via a Dart-side timeout, not in Rust.
 *
 * Returns [`ARTI_OK`] on success, [`ARTI_ERR_BOOTSTRAP`] on failure.
 */
int arti_bootstrap(ArtiHandle *handle);

/**
 * Returns the local SOCKS5 port Arti uses for outbound connections, or 0
 * if the SOCKS proxy isn't running. Used by Plan 11b to route the Dart
 * `http.Client` through Tor.
 */
uint16_t arti_socks_port(ArtiHandle *handle);

/**
 * Fill `out` with the latest status snapshot. Returns [`ARTI_OK`] or a
 * negative error code. `out` must point to a writable [`ArtiStatus`].
 */
int arti_status(ArtiHandle *handle, ArtiStatus *out);

/**
 * Drop the handle, tear down the runtime, and unpublish the onion
 * service. After this call, `handle` MUST NOT be used again.
 */
int arti_shutdown(ArtiHandle *handle);

/**
 * Free a string returned by [`arti_create_onion_service`].
 */
void arti_string_free(char *s);

/**
 * Initialize the libp2p bridge and return an opaque handle.
 *
 * - `data_dir`: filesystem path for libp2p PeerStore caches (no secrets).
 * - `seed_ptr`/`seed_len`: 32-byte Ed25519 seed. The bridge copies the
 *   seed into Rust, constructs the keypair, and zeroizes its copy. The
 *   caller MUST zeroize its buffer immediately on return.
 * - `post_c_object_fn_ptr`: pointer obtained from
 *   `NativeApi.postCObject` on the Dart side. Stored process-globally via
 *   `allo-isolate` so the event loop can `Dart_PostCObject(port, msg)`
 *   from non-isolate tokio threads. Pass NULL to disable event delivery
 *   (tests that don't care about Swarm events).
 *
 * Returns NULL on failure with [`lp_last_error`] populated.
 */
LpHandle *lp_init(const char *data_dir,
                  const uint8_t *seed_ptr,
                  uintptr_t seed_len,
                  void *post_c_object_fn_ptr);

/**
 * Bind UDP/QUIC listeners on `/ip4/0.0.0.0/udp/0/quic-v1` and start the
 * swarm event loop. Idempotent.
 */
int lp_listen(LpHandle *handle);

/**
 * Write a CBOR-encoded list of currently-observed external multiaddrs
 * into `out_buf`. Returns the number of bytes written or
 * [`LP_ERR_BUFFER_TOO_SMALL`].
 */
intptr_t lp_observed_addrs(LpHandle *handle, uint8_t *out_buf, uintptr_t buf_len);

/**
 * Inject an externally observed multiaddr.
 */
int lp_add_observed_addr(LpHandle *handle, const uint8_t *multiaddr_ptr, uintptr_t len);

/**
 * Issue a DCUtR-aware direct dial. Returns a positive connection id or
 * a negative [`LP_ERR_*`].
 */
int64_t lp_dial_direct(LpHandle *handle,
                       const char *peer_id_cstr,
                       const uint8_t *addrs_cbor,
                       uintptr_t addrs_len,
                       uint32_t timeout_ms);

/**
 * Open a libp2p stream for `protocol_cstr` over an existing connection.
 * Returns a positive stream id or a negative [`LP_ERR_*`].
 */
int64_t lp_open_stream(LpHandle *handle, int64_t conn_id, const char *protocol_cstr);

/**
 * Write one length-delimited frame to a stream.
 */
int lp_stream_write(LpHandle *handle,
                    int64_t stream_id,
                    const uint8_t *data_ptr,
                    uintptr_t len,
                    bool finish);

/**
 * Read exactly one length-delimited frame. Returns bytes written into
 * `out_buf`, or a negative [`LP_ERR_*`].
 */
intptr_t lp_stream_read(LpHandle *handle,
                        int64_t stream_id,
                        uint8_t *out_buf,
                        uintptr_t buf_len,
                        uint32_t timeout_ms);

/**
 * Close a stream.
 */
int lp_stream_close(LpHandle *handle, int64_t stream_id);

/**
 * Register a Dart Native Port for event delivery.
 */
int lp_set_event_port(LpHandle *handle, int64_t native_port);

/**
 * Register an inbound stream handler for `protocol_cstr`.
 */
int lp_register_inbound_handler(LpHandle *handle, const char *protocol_cstr);

/**
 * Returns the local base58-encoded PeerId. Caller frees with
 * [`lp_string_free`]. Returns NULL before [`lp_init`].
 */
char *lp_local_peer_id(LpHandle *handle);

/**
 * Stop the swarm event loop and close all listeners.
 */
int lp_shutdown(LpHandle *handle);

/**
 * Most recent error message on this thread. Caller frees with
 * [`lp_string_free`].
 */
char *lp_last_error(void);

/**
 * Free a string returned by the bridge.
 */
void lp_string_free(char *ptr);

#endif  /* STARLING_BRIDGE_H */
